sources:
  docker_logs:
    type: docker_logs
    include_containers:
      - homeassistant
      - appdaemon
      - dnscrypt-1
  openwrt_syslog:
    type: syslog
    mode: udp
    address: "0.0.0.0:514"
