#title: My Awesome Home
# Include external resources
#resources:
#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
    # View tab title.
  - title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: main
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
           - device_tracker.daniel_phone
           - device_tracker.hhaim_phone
           - device_tracker.nitay_phone
           - device_tracker.nitay_pc
           - device_tracker.rivi_phone
           - device_tracker.sony_ps
           - device_tracker.tv

        state_filter:
          - 'home'
        card:
          type: glance
      
      - type: glance
        entities:
          - entity: switch.b0
            name: Boiler-On
            icon: mdi:shower
          - entity: sensor.btemp0
            name: Boiler
            icon: mdi:oil-temperature
          - entity: variable.heat_index0
            name: Down
            icon: mdi:oil-temperature
          - entity: variable.heat_index1
            name: Up
            icon: mdi:oil-temperature
          - entity: variable.heat_index_outside0
            name: Outside
            icon: mdi:oil-temperature
          - entity: sensor.uptime
            name: uptime
          - entity: sensor.water_total_external_norm
            name: Water 
          - entity: sensor.wb_irrigation_p1
            name: Pipe1
          - entity: sensor.wb_irrigation_p2
            name: Pipe2
          - entity: sensor.wb_irrigation_rain
            name: Rain

      - type: entities
        show_header_toggle: true
        entities:
          - switch.tv
          - switch.ac1
          - switch.ac2

      - type: entity-filter
        entities:
          - device_tracker.cam1
          - device_tracker.cam2
          - device_tracker.cam3
          - device_tracker.cam4
          - device_tracker.cam5
          - device_tracker.alarm

        state_filter:
          - 'not_home'
        card:
          type: glance
          title: Camera issues


  - title: A/C
    id: ac
    theme: dark-mode
    background: radial-gradient(lightgreen, skyblue)
    cards:
      - type: entities
        title: A/C
        show_header_toggle: true
        entities:
          - variable.heat_index0
          - variable.heat_index1
          - variable.heat_index_outside0
          - switch.ac1
          - switch.ac2
      - type: entities
        title: Automation
        entities:
          - input_boolean.heat_app_enable
          - input_boolean.heat_timer_0
          - input_number.heat_timer_time
      - type: history-graph
        title: graph 
        hours_to_show : 24
        entities:
          - variable.heat_index0
          - variable.heat_index1
          - variable.heat_index_outside0
          - switch.ac1
          - switch.ac2

  - title: Debug
    id: debug
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: Machine
        show_header_toggle: true
        entities:
           - group.cpu
           - switch.power0
           - input_boolean.simple_switch0
           - input_boolean.disable_ap_c7
           - input_boolean.gateway_sound_enable
           - input_number.gateway_sound_id
           - binary_sensor.cube_158d000276ed22
           - sensor.tv_hours
           - sensor.water_total
           - sensor.water_total_external
           - light.gateway_light_7c49eb193b55
           - light.light1

  - title: Camera
    id: cam
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        title: cam
        show_header_toggle: true
        entities:
          - camera.cam5
          - camera.cam1
          - camera.cam2
          - camera.cam3
          - camera.cam4
          

  - title: Alarm
    id: alarm
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entity-filter
        entities:
            - binary_sensor.alarm0
            - binary_sensor.alarm1
            - binary_sensor.alarm2
            - binary_sensor.alarm3
            - binary_sensor.alarm4
            - binary_sensor.alarm5
            - binary_sensor.alarm6
            - binary_sensor.alarm7
            - binary_sensor.alarm8
            - binary_sensor.alarm14
            - binary_sensor.alarm15
            - binary_sensor.alarm16
            - binary_sensor.smoke_sensor_158d00024e008a
            - binary_sensor.smoke_sensor_158d000287ae79
            - binary_sensor.water_leak_sensor_158d000256cd9d
            - binary_sensor.water_leak_sensor_158d00023385f2
            - binary_sensor.water_leak_sensor_158d000256ce72
            - binary_sensor.water_leak_sensor_158d000256ce93
            - binary_sensor.water_leak_sensor_158d000256cede
            - binary_sensor.water_leak_sensor_158d00027049bb
            - binary_sensor.motion_sensor_158d0002b48209     
            - binary_sensor.motion_sensor_158d0002b75328     
            - binary_sensor.motion_sensor_158d0002b75423     
            - binary_sensor.motion_sensor_158d0002b7d400     
            - binary_sensor.motion_sensor_158d0002b7d548     
            - binary_sensor.motion_sensor_158d0002b7f8b4     
            - binary_sensor.motion_sensor_158d0002b85a33     
            - binary_sensor.motion_sensor_158d0002c7165a     
        state_filter:
              - 'on'
        card:
          type: glance
          title: sensors

      - type: history-graph
        title: graph 
        hours_to_show : 1
        entities:
            - binary_sensor.alarm0
            - binary_sensor.alarm1
            - binary_sensor.alarm2
            - binary_sensor.alarm3
            - binary_sensor.alarm4
            - binary_sensor.alarm5
            - binary_sensor.alarm6
            - binary_sensor.alarm7
            - binary_sensor.alarm8
            - binary_sensor.alarm14
            - binary_sensor.alarm15
            - binary_sensor.alarm16
            - binary_sensor.smoke_sensor_158d00024e008a
            - binary_sensor.smoke_sensor_158d000287ae79
            - binary_sensor.water_leak_sensor_158d000256cd9d
            - binary_sensor.water_leak_sensor_158d00023385f2
            - binary_sensor.water_leak_sensor_158d000256ce72
            - binary_sensor.water_leak_sensor_158d000256ce93
            - binary_sensor.water_leak_sensor_158d000256cede
            - binary_sensor.water_leak_sensor_158d00027049bb
            - binary_sensor.motion_sensor_158d0002b48209     
            - binary_sensor.motion_sensor_158d0002b75328     
            - binary_sensor.motion_sensor_158d0002b75423     
            - binary_sensor.motion_sensor_158d0002b7d400     
            - binary_sensor.motion_sensor_158d0002b7d548     
            - binary_sensor.motion_sensor_158d0002b7f8b4     
            - binary_sensor.motion_sensor_158d0002b85a33     
            - binary_sensor.motion_sensor_158d0002c7165a     
      
      - type: entities
        title: Alarm control 
        show_header_toggle: true
        entities:
          - switch.alarm_s0
          - switch.alarm_s1

  - title: Boiler
    id: boiler
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        entities:
          - sensor.btemp0
          - switch.b0
          - input_boolean.boiler_auto_enable
          - input_number.boiler_timer_time
          - input_number.boiler_temp_min
          - input_number.boiler_temp_max
          - sensor.boiler_total_hours
          - sensor.boiler_total_hours2
          - sensor.stats_mean
      - type: history-graph
        title: graph 
        hours_to_show : 24
        entities:
          - sensor.btemp0
          - switch.b0

  - title: Irrigation
    id: Irrigation
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: glance
        entities:
          - entity: switch.wbi_p1
            name: tap1
          - entity: switch.wbi_p2
            name: tap2
          - entity: sensor.wb_irrigation_p1
            name: Pipe1
          - entity: sensor.wb_irrigation_p2
            name: Pipe2
          - entity: sensor.wb_irrigation_rain
            name: Rain
          - entity: sensor.wbi_p1_hours
            name: hours
          - entity: sensor.wbi_p2_hours
            name: hours
          - entity: variable.wbi_water_p1
            name: l
          - entity: variable.wbi_water_p2
            name: l

      - type: entities
        entities:
          - sensor.wb_irrigation_ev_day
          - sensor.wb_irrigation_rain_day
          - input_number.wbi_p1_duration
          - input_number.wbi_p2_duration
          - input_boolean.wbi_enabled

      - type: history-graph
        title: graph 
        hours_to_show : 168
        entities:
          - sensor.wb_irrigation_ev_day
          - sensor.wb_irrigation_rain
          - sensor.wb_irrigation_rain_day
          - sensor.wb_irrigation_p1
          - sensor.wb_irrigation_p2

