
## Customize
homeassistant:
  customize:
    input_boolean.heat_app_enable:
      friendly_name: Start Automation 
      icon: mdi:air-conditioner

    input_boolean.heat_app_enable_base:
      friendly_name: Start Automation Basement
      icon: mdi:air-conditioner

    switch.ac1:
      friendly_name: A/C-Down
      icon: mdi:air-conditioner

    switch.ac2:
      friendly_name: A/C-Up
      icon: mdi:air-conditioner

    switch.ac3:
      friendly_name: A/C-Base
      icon: mdi:air-conditioner

group: 

  air_conditioner:
    name: Air Conditioner
    entities:
       - variable.heat_index0
       - variable.heat_index1
       - variable.heat_index2
       - variable.heat_index_outside0
       - switch.ac1
       - switch.ac2
       - switch.ac3
       - switch.tv
       - media_player.main
       - media_player.kodi
       - sensor.water_total_external_norm


  air_conditioner_automation:
       name: Automation
       entities:
         - input_boolean.heat_app_enable
         - input_boolean.heat_timer_0
         - input_number.heat_timer_time



input_boolean:
  heat_app_enable:
    name: Enable AC/1 Heater
  heat_app_enable_base:
    name: Enable AC/Base Heater
  heat_timer_0:
    name: Enable timer for heat

input_number:
  heat_timer_time:
    name: A/C Timer
    min: 60
    max: 240
    step: 30


switch:
  - platform: tasmota
    name: ac1
    index: '1'
    stopic: s0

  - platform: tasmota
    name: ac2
    index: '1'
    stopic: s1

  # basement 
  - platform: tasmota
    name: ac3  
    stopic: temp2

sensor:

  - platform: accumulator
    name: ac1_hours
    entity_id: switch.ac1
    state_on: 'on'
    state_off: 'off'

  - platform: accumulator
    name: ac2_hours
    entity_id: switch.ac2
    state_on: 'on'
    state_off: 'off'

  - platform: accumulator
    name: ac3_hours
    entity_id: switch.ac3
    state_on: 'on'
    state_off: 'off'





