
homeassistant:
  customize:
    switch.wbi_p1:
      friendly_name: p1
      icon: mdi:water-pump

    switch.wbi_p2:
      friendly_name: p2
      icon: mdi:water-pump
    

# sensors for weather based irrigation 
# calculation factors based on rain and evaporation model
wb_irrigation:
  api_key: !secret openweathermap_key
  rain_factor: 90
  max_ev: 3000 
  min_ev: -1500.0
  name: "wb_irrigation"
  #debug: true 
  longitude: !secret accurate_longitude
  latitude: !secret accurate_latitude
  elevation: !secret accurate_elevation
  taps: 
    - name: p1
    - name: p2

# manual duration time in minutes 
input_number:
  wbi_p1_duration:
    name: p1
    min: 5
    max: 15
    step: 1.0
    unit_of_measurement: min
    icon: mdi:timer-sand 

  wbi_p2_duration:
    name: p2
    min: 5.0
    max: 25.0
    step: 1.0
    unit_of_measurement: min
    icon: mdi:timer-sand 

  wbi_week_p1_duration:  #week total time
    name: wp1
    min: 0.0
    max: 400
    step: 0.5
    unit_of_measurement: min
    icon: mdi:timer-sand 
  
  wbi_week_p2_duration: #week total time
    name: wp2
    min: 0.0
    max: 60.0
    step: 0.5
    unit_of_measurement: min
    icon: mdi:timer-sand 


input_boolean:
  wbi_enabled:
    name: Enable irrigation 

# switch to manual turn on off 
switch:

  - platform: tasmota
    name: wbi_p1
    index: '1'
    stopic: irrigation

  - platform: tasmota
    name: wbi_p2
    index: '2'
    stopic: irrigation


variable:

      wbi_water_p1:
        value: 0
        restore: true
        attributes:
           friendly_name: 'water pump 1'
           unit_of_measurement: "l"

      wbi_water_p2:
        value: 0
        restore: true
        attributes:
           friendly_name: 'water pump 2'
           unit_of_measurement: "l"

      wbi_last_duration_p1:
        value: 0
        restore: true
        attributes:
           friendly_name: 'last duration pump 1'
           unit_of_measurement: "min"
      
      wbi_last_duration_p2:
        value: 0
        restore: true
        attributes:
           friendly_name: 'last duration pump 1'
           unit_of_measurement: "min"

      wbi_schedule_p1:
        value: 0
        restore: true
        attributes:
           friendly_name: 'P1 Schedule'

      wbi_schedule_p2:
        value: 0
        restore: true
        attributes:
           friendly_name: 'P2 Schedule'


sensor:

  - platform: accumulator
    name: wbi_p1_hours
    entity_id: switch.wbi_p1
    state_on: 'on'
    state_off: 'off'

  - platform: accumulator
    name: wbi_p2_hours
    entity_id: switch.wbi_p2
    state_on: 'on'
    state_off: 'off'

    #alternative to accumulator above
  - platform: history_stats
    name: wbi_p1_history_today
    entity_id: switch.wbi_p1
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p1_history_yesterday
    entity_id: switch.wbi_p1
    state: 'on'
    type: time
    end: '{{ now().replace(hour=0, minute=0, second=0) }}'
    duration:
      hours: 24
  - platform: history_stats
    name: wbi_p1_history_week
    entity_id: switch.wbi_p1
    state: 'on'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p1_history_month
    entity_id: switch.wbi_p1
    state: 'on'
    type: time
    start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p1_history_year
    entity_id: switch.wbi_p1
    state: 'on'
    type: time
    start: '{{ now().replace(month=1).replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: wbi_p2_history_today
    entity_id: switch.wbi_p2
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p2_history_yesterday
    entity_id: switch.wbi_p2
    state: 'on'
    type: time
    end: '{{ now().replace(hour=0, minute=0, second=0) }}'
    duration:
      hours: 24
  - platform: history_stats
    name: wbi_p2_history_week
    entity_id: switch.wbi_p2
    state: 'on'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p2_history_month
    entity_id: switch.wbi_p2
    state: 'on'
    type: time
    start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: wbi_p2_history_year
    entity_id: switch.wbi_p2
    state: 'on'
    type: time
    start: '{{ now().replace(month=1).replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
