

switch:

  - platform: tasmota
    name: door-lamp0
    stopic: basic1

  - platform: tasmota
    name: garden-lamp0
    stopic: basic0

  - platform: tasmota
    name: gardenlamp1
    stopic: basic2

  - platform: tasmota
    name: r0table
    stopic: basic3

  - platform: tasmota
    name: r0tv
    stopic: basic4

  - platform: tasmota
    name: shutter2
    stopic: shutter2
    index: '2'

  - platform: tasmota
    name: shutter3
    stopic: shutter3
    index: '1'

  - platform: tasmota
    name: shutter4
    stopic: shutter4
    index: '1'

  - platform: tasmota
    name: rshutter11
    stopic: shutter1
    index: '1'

  - platform: tasmota
    name: rshutter12
    stopic: shutter1
    index: '2'

  - platform: template
    switches:
      shutter11:
        friendly_name: shutter11
        value_template: "{{ is_state('switch.rshutter11', 'off') }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.rshutter11
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.rshutter11
      shutter12:
        friendly_name: shutter12
        value_template: "{{ is_state('switch.rshutter12', 'off') }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.rshutter12
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.rshutter12

group: 
  shutter_r0:
    name: sr0
    entities:
        - switch.shutter11
        - switch.shutter12
        - switch.shutter3
        - switch.shutter2
        - switch.shutter4
  lamps_r0:
    name: lr0
    entities:
        - switch.r0table
        - switch.r0tv

binary_sensor: 

  - platform: mqtt
    name: "alarm16"
    payload_on: "OFF"
    payload_off: "ON"
    availability_topic: "tele/basic1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "cmnd/basic1-status/POWER2"



light:
  - platform: mqtt
    name: "Light1"
    command_topic: "cmnd/rgb1/POWER"
    state_topic: "stat/rgb1/RESULT"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/rgb1/LWT"
    brightness_command_topic: "cmnd/rgb1/Dimmer"
    brightness_state_topic: "stat/rgb1/RESULT"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    rgb_command_topic: "cmnd/rgb1/Color2"
    rgb_state_topic: "stat/rgb1/RESULT"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/rgb1/Scheme"
    effect_state_topic: "stat/rgb1/RESULT"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false


