
variable:
      water_leak_detector:
        value: 0
        restore: true
        attributes:
          friendly_name: 'water leaks detector'
          unit_of_measurement: "l"

      water_bursts:
        value: 0
        restore: true
        attributes:
          friendly_name: 'water usage in bulks'
          unit_of_measurement: "l"


sensor:

  - platform: tasmota
    name: water_total
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (45497 + (value))|int }}"

  - platform: tasmota
    name: water_total_external
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (80600 + 45497 + (value))|int }}"

  - platform: tasmota
    name: water_total_norm
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (37950 + (value/1.05))|int }}"

  - platform: tasmota
    name: water_total_external_norm
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (198900 + (value/1.05))|int }}"
    


