
variable:
      heat_index0:
        value: 0
        restore: true
        attributes:
          friendly_name: 'Heat Index first floor'
          unit_of_measurement: "C"
      
      heat_index1:
        value: 0
        restore: true
        attributes:
          friendly_name: 'Heat Index second floor'
          unit_of_measurement: "C"

      heat_index2:
        value: 0
        restore: true
        attributes:
          friendly_name: 'Heat Index basement floor'
          unit_of_measurement: "C"

      heat_index_outside0:
        value: 0
        restore: true
        attributes:
          friendly_name: 'Index outside'
          unit_of_measurement: "C"


# Weather prediction
sensor:

  - platform: mqtt
    name: "Temperature"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "C"

  - platform: mqtt
    name: "Humidity"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "temp1"
    state_topic: "tele/temp0/SENSOR"
    value_template: "{{ value_json['SI7021'].Temperature }}"
    unit_of_measurement: "C"

  - platform: mqtt
    name: "hum1"
    state_topic: "tele/temp0/SENSOR"
    value_template: "{{ value_json['SI7021'].Humidity }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "temp2"
    state_topic: "tele/temp2/SENSOR"
    value_template: "{{ value_json['SI7021'].Temperature }}"
    unit_of_measurement: "C"

  - platform: mqtt
    name: "hum2"
    state_topic: "tele/temp2/SENSOR"
    value_template: "{{ value_json['SI7021'].Humidity }}"
    unit_of_measurement: "%"

  
  




