variable:
      water_leak_detector:
        value: 0
        restore: true
        attributes:
          friendly_name: 'water leaks detector'
          unit_of_measurement: "l"

      water_bursts:
        value: 0
        restore: true
        attributes:
          friendly_name: 'water usage in bulks'
          unit_of_measurement: "l"


template:
  - sensor:
      - name: water_total_external
        unit_of_measurement: 'l'
        icon: mdi:water-pump
        availability: >
          {{ states('sensor.water_total') not in ['unavailable', 'unknown'] and 
          states('sensor.water_total') | float(0) > 0 }}
        state_class: measurement
        state: >
          {% set source = states('sensor.water_total') | float(0) %}
          {{ (80600 + 45497 + (source )) | int }}

      - name: water_total_norm
        unit_of_measurement: 'l'
        availability: >
          {{ states('sensor.water_total') not in ['unavailable', 'unknown'] and 
          states('sensor.water_total') | float(0) > 0 }}
        icon: mdi:water-pump
        state_class: measurement
        state: >
          {% set source = states('sensor.water_total') | float(0) %}
          {{ (357120 + (source /1.05)) | int }}

      - name: water_total_external_norm
        unit_of_measurement: 'l'
        icon: mdi:water-pump
        availability: >
          {{ states('sensor.water_total') not in ['unavailable', 'unknown'] and 
          states('sensor.water_total') | float(0) > 0 }}
        state_class: measurement
        state: >
          {% set source = states('sensor.water_total') | float(0) %}
          {{ (692437 + (source /1.05)) | int }}


sensor:

  - platform: mytasmota
    name: water_total
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (45497 + (value))|int }}"


    


