homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret accurate_latitude
  longitude: !secret accurate_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 43
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  auth_providers:
      - type: homeassistant
      - type: legacy_api_password
        api_password: !secret http_password
  customize: !include customize.yaml

  packages: !include_dir_named pkgs

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  #trusted_networks:
  #      - 127.0.0.1
  #      - 10.0.0.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#logger:
#  default: critical
#  logs:
#    homeassistant.components.xiaomi_aqara: debug
#    xiaomi_gateway: debug

    

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


#duckdns:
#  domain: !secret duckdns_domain 
#  access_token: !secret duckdns_tocken

duckdns_ipv4_ipv6:
  access_token: !secret duckdns_tocken
  domain: !secret duckdns_domain 
  ipv4_mode: duckdns
  ipv6_mode: nameserver

# Example configuration.yaml entry
#speedtestdotnet:
#  scan_interval:
#    minutes: 60
#  monitored_conditions:
#    - ping
#    - download
#    - upload


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

#  platform: pushbullet
#  api_key: !secret pushbullet

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: notify
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

  - platform: clicksend
    name: ClickSend
    username: !secret clicksend_user
    api_key: !secret clicksend_api
    recipient: !secret clicksend_phones
    sender: !secret clicksend_sener

  - platform: clicksend_tts_en
    name: clicksend_tts
    username: !secret clicksend_user
    api_key: !secret clicksend_api
    recipient: !secret clicksend_phone
    caller: !secret clicksend_sener

  - platform: clicksend_tts_en
    name: clicksend_tts2
    username: !secret clicksend_user
    api_key: !secret clicksend_api
    recipient: !secret clicksend_phone2
    caller: !secret clicksend_sener


recorder:
  purge_keep_days: 2
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - device_tracker
    entities:
      - group.room0
      - switch.door_lamp0
      - switch.garden_lamp0
      - switch.ac3
  include:
    entities:
      - device_tracker.hhaim_phone
      - device_tracker.daniel_phone
      - device_tracker.nitay_phone
      - device_tracker.nitay_pc
      - device_tracker.rivi_phone
      - device_tracker.sony_ps
      - device_tracker.tv
      - device_tracker.tv_wifi
      - device_tracker.daniel_phone1
      - device_tracker.daniel_phone2
      - variable.tracker_neta


#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#      -  mac: !secret mii_mac
#         key: !secret mii_key 

hebcal:
#  debug: true

system_health:


influxdb:
  host: !secret local_host
  port: 8428
  username: !secret influx_user
  password: !secret influx_password
  database: hass_db
  exclude:
    domains:
      - binary_sensor
      - device_tracker
    entities:
      - switch.door_lamp0
      - switch.garden_lamp0
      - group.room0
      - switch.ac3
  
  include:
    entities:
      - binary_sensor.google
      - binary_sensor.home
      - binary_sensor.cloudflare

prometheus:
  namespace: hass
  filter:
    include_domains:
      - sensor

# Example configuration.yaml entry for template platform
sensor:

  - platform: template
    sensors:
      se_energy_year:
        value_template: "{{ (states('sensor.solaredge_energy_this_year') | float / 1000) | round(0) }}"
      se_energy_month:
        value_template: "{{ (states('sensor.solaredge_energy_this_month') | float / 1000) | round(0) }}"
      se_energy_day:
        value_template: "{{ (states('sensor.solaredge_energy_today') | float / 1000) | round(0) }}"
      se_energy_cur:
        value_template: "{{ (states('sensor.solaredge_current_power') | float / 1000) | round(0) }}"
       
lovelace:
  ## put here
  mode: yaml
  resources:
    - url: /local/multiple-entity-row.js?v=4.2.0
      type: module


automation: !include automations.yaml
script: !include scripts.yaml
