services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.17.1-tensorrt
    restart: unless-stopped
    privileged: true

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - FRIGATE_RTSP_PASSWORD=changeme        # referenced in config as {FRIGATE_RTSP_PASSWORD}

    # shm_size = (Width * Height * 1.5 * num_cameras) / 1024 / 1024
    # For 1x 1080p camera ~3MB, 256mb is plenty. Increase for more cameras or 4K.
    shm_size: "1024mb"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/frigatedata/storage:/media/frigate

    tmpfs:
      - /tmp/cache:size=1073741824           # 1GB tmpfs for video clip cache

    ports:
      - "5000:5000"      # Web UI
      - "8554:8554"      # RTSP restream (go2rtc)
      - "8555:8555/tcp"  # WebRTC
      - "8555:8555/udp"  # WebRTC

    devices:
      - /dev/dri:/dev/dri                    # keep for potential VAAPI fallback

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility, video]

  #neolink:
  #  image: quantumentangledandy/neolink:v0.6.2
  #  container_name: neolink
  #  restart: unless-stopped
  #  network_mode: host          # required for local UDP broadcast camera discovery
  #  volumes:
  #    - ./neolink.toml:/etc/neolink.toml:ro
  #  environment:
  #    - NEO_LINK_MODE=rtsp # rtsp | mqtt | mqtt-rtsp
  #    - NEO_LINK_PORT=8554
  #    - RUST_LOG=info           # change to debug when troubleshooting

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host
      - --collector.hwmon
      - --collector.cpu
      - --collector.thermal_zone

  nvidia_gpu_exporter:
    image: utkuozdemir/nvidia_gpu_exporter:1.2.0
    container_name: nvidia_gpu_exporter
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:9835/metrics"]
        interval: 30s
        retries: 3
        start_period: 10s

    ports:
      - "9835:9835"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]